name: Build and Export Artifact on Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Run build script
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run build.bat
        run: .\build.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FiveM ReShade Setup
          path: output/setup.exe
          if-no-files-found: error
          compression-level: 9

  add-to-release:
    name: Add Artifact to Release
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: FiveM ReShade Setup

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: FiveM ReShade Setup/setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
